kind = "mobile"
previewPath = "/mobile/"
title = "Ciyato Mobile"
version = "1.0.0"
id = "artifacts/ciyato-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 20965

[services.development]
run = "pnpm --filter @workspace/ciyato-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ciyato-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ciyato-mobile", "run", "serve" ]

[services.env]
PORT = "20965"
BASE_PATH = "/mobile/"
